/**
 * .imagine <prompt> — image fetcher / AI generator
 *
 * Order of providers (first success wins):
 *   1. Unsplash (PRIMARY)  — high-quality real photos matching the prompt
 *   2. lolhuman imagine    — AI image fallback
 *   3. prexzyapis DALL·E  — AI image fallback
 *
 * Aliases: .aiimage, .genimage, .create
 */
const axios = require('axios');

const UNSPLASH_ACCESS_KEY = process.env.UNSPLASH_ACCESS_KEY ||
    'e306xjYAc9h7E2BhXf8gACkiykLBTg23KDIad9bqeTk';

async function tryUnsplash(prompt) {
    try {
        const { data } = await axios.get('https://api.unsplash.com/photos/random', {
            params: { query: prompt, orientation: 'squarish', count: 1 },
            headers: { Authorization: `Client-ID ${UNSPLASH_ACCESS_KEY}` },
            timeout: 30000,
        });
        const item = Array.isArray(data) ? data[0] : data;
        const url  = item?.urls?.regular || item?.urls?.full || item?.urls?.small;
        if (!url) return null;
        const res = await axios.get(url, { responseType: 'arraybuffer', timeout: 60000 });
        const buf = Buffer.from(res.data);
        if (!buf || buf.length < 1024) return null;
        return {
            buf,
            credit: item?.user?.name ? `Photo by ${item.user.name} on Unsplash` : 'Unsplash',
            model: 'Unsplash',
        };
    } catch (e) {
        console.error('[imagine] Unsplash failed:', e.message);
        return null;
    }
}

async function tryLolhuman(prompt) {
    try {
        const url = `https://api.lolhuman.xyz/api/imagine?apikey=free&prompt=${encodeURIComponent(prompt)}`;
        const res = await axios.get(url, { responseType: 'arraybuffer', timeout: 60000 });
        const buf = Buffer.from(res.data);
        if (!buf || buf.length < 1024) return null;
        return { buf, credit: null, model: 'lolhuman' };
    } catch (e) {
        console.error('[imagine] lolhuman failed:', e.message);
        return null;
    }
}

async function tryDalle(prompt) {
    try {
        const { data } = await axios.get('https://prexzyapis.com/ai/dalle', {
            params: { prompt }, timeout: 60000,
        });
        if (!data || data.status !== true) return null;
        const arr = data.image_url || data.images || data.result;
        let url = null;
        if (Array.isArray(arr) && arr.length) {
            const first = arr[0];
            url = first?.image?.url || first?.url || (typeof first === 'string' ? first : null);
        }
        url = url || (typeof data.result === 'string' ? data.result : null) ||
                    (typeof data.url === 'string' ? data.url : null);
        if (!url) return null;
        const res = await axios.get(url, { responseType: 'arraybuffer', timeout: 60000 });
        const buf = Buffer.from(res.data);
        if (!buf || buf.length < 1024) return null;
        return { buf, credit: null, model: 'DALL·E 3 XL' };
    } catch (e) {
        console.error('[imagine] dalle failed:', e.message);
        return null;
    }
}

module.exports = {
    name: 'imagine',
    aliases: ['aiimage', 'genimage', 'create'],
    description: 'Fetch / generate an image from text (.imagine <prompt>)',
    category: 'ai',

    async execute({ sock, msg, from, reply, args }) {
        if (!args.length) {
            return reply(
                `🎨 *Image Generator*\n\n` +
                `Usage: .imagine <description>\n` +
                `Example: .imagine a cat wearing a spacesuit on the moon`
            );
        }

        const prompt = args.join(' ').trim();
        await reply('🎨 *Fetching image...* please wait.');

        let r = await tryUnsplash(prompt);
        if (!r) r = await tryLolhuman(prompt);
        if (!r) r = await tryDalle(prompt);

        if (!r) {
            return reply('❌ All image providers failed. Please try a different prompt.');
        }

        const creditLine = r.credit ? `\nCredit: ${r.credit}` : '';
        try {
            await sock.sendMessage(from, {
                image: r.buf,
                caption: `🎨 *Image Result*\n\nPrompt: ${prompt}\nSource: ${r.model}${creditLine}\n\n> Generated by SUKUNA MD`,
            }, { quoted: msg });
        } catch (err) {
            reply(`❌ Failed to send image: ${err.message}`);
        }
    },
};
