/**
 * textmakerFetch — text-effect helper backed by mumaker + ephoto360.
 *
 * Adopts the exact KnightBot pattern: every effect maps to an ephoto360
 * URL handed to `mumaker.ephoto(url, text)`, returning { image }.
 * The factory below wraps that flow so each command file stays one line.
 */
'use strict';

const mumaker = require('mumaker');

// SUKUNA MD channel pill — attached to every textmaker reply.
const channelInfo = {
    forwardingScore: 1,
    isForwarded: true,
    forwardedNewsletterMessageInfo: {
        newsletterJid:  '120363424109748354@newsletter',
        newsletterName: 'Sukuna MD Pasqua tech',
        serverMessageId: -1,
    },
};

const messageTemplates = {
    error: (text) => ({ text, contextInfo: channelInfo }),
    success: (imageUrl, caption) => ({
        image:   { url: imageUrl },
        caption: caption || 'GENERATED BY SUKUNA MD',
        contextInfo: channelInfo,
    }),
};

async function fetchEphoto(url, text) {
    const result = await mumaker.ephoto(url, text);
    if (!result || !result.image) throw new Error('No image URL received from the API');
    return result.image;
}

function makeTextmakerCommand({ name, ephotoUrl, label, emoji = '✨', aliases = [] }) {
    return {
        name,
        aliases,
        description: `${label} text effect`,
        category: 'textmaker',
        async execute({ sock, msg, from, reply, args }) {
            if (!args.length) {
                return sock.sendMessage(
                    from,
                    messageTemplates.error(
                        `${emoji} *${label}*\n\nUsage: .${name} <text>\nExample: .${name} SUKUNA`
                    ),
                    { quoted: msg }
                );
            }
            const text = args.join(' ').trim().slice(0, 60);
            try {
                await sock.sendMessage(from, { react: { text: '⏳', key: msg.key } });
                const imageUrl = await fetchEphoto(ephotoUrl, text);
                const caption  = `${emoji} *${label}* — ${text}\n\n> SUKUNA MD`;
                await sock.sendMessage(
                    from,
                    messageTemplates.success(imageUrl, caption),
                    { quoted: msg }
                );
                await sock.sendMessage(from, { react: { text: '✅', key: msg.key } });
            } catch (err) {
                console.error(`[${name}] error:`, err.message);
                try { await sock.sendMessage(from, { react: { text: '❌', key: msg.key } }); } catch {}
                await sock.sendMessage(
                    from,
                    messageTemplates.error(`❌ ${label} failed: ${err.message}`),
                    { quoted: msg }
                );
            }
        },
    };
}

module.exports = { fetchEphoto, makeTextmakerCommand, messageTemplates, channelInfo };
